#!/bin/sh
set -eu

ROOT="$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)"
TMP="${TMPDIR:-/tmp}/dotfiles-e2e-agent-rule-scopes-$$"
STALE_RULE="$ROOT/cursor/rules/stale-scope-test.mdc"
trap 'rm -rf "$TMP"; rm -f "$STALE_RULE"' EXIT INT TERM

fail() {
    printf 'FAIL: %s\n' "$*" >&2
    exit 1
}

assert_contains() {
    grep -qF "$2" "$1" || fail "$1 does not contain $2"
}

assert_excludes() {
    if grep -qF "$2" "$1"; then
        fail "$1 unexpectedly contains $2"
    fi
}

vanta_heading="## Vanta Work Repositories"
local_dev_heading="## Local Dev Environment"
verification_heading="## Verification & PR Handoff"
mcp_heading="## MCP Server Preferences"

for file in "$ROOT/claude/CLAUDE.md" "$ROOT/codex/AGENTS.md" "$ROOT/opencode/AGENTS.md"; do
    assert_excludes "$file" "$vanta_heading"
    assert_excludes "$file" "$local_dev_heading"
    assert_excludes "$file" "$verification_heading"
    assert_excludes "$file" "$mcp_heading"
done

for file in "$ROOT/claude/CLAUDE-work.md" "$ROOT/codex/AGENTS-work.md" "$ROOT/opencode/AGENTS-work.md"; do
    assert_contains "$file" "$vanta_heading"
    assert_contains "$file" "$local_dev_heading"
    assert_contains "$file" "$verification_heading"
    assert_contains "$file" "$mcp_heading"
done

[ ! -e "$ROOT/cursor/rules/vanta-work.mdc" ] || fail "personal Cursor rules include Vanta guidance"
[ -f "$ROOT/cursor/rules-work/vanta-work.mdc" ] || fail "work Cursor rules omit Vanta guidance"
grep -qx 'setup_codex_config' "$ROOT/install.sh" || fail "Codex setup still depends on RTK setup"

printf '%s\n' '<!-- GENERATED by agent-rules/build.py from agent-rules/*.md - edit those and run `python3 agent-rules/build.py`; do not hand-edit this file. -->' >"$STALE_RULE"
if python3 "$ROOT/agent-rules/build.py" --check >/dev/null 2>&1; then
    fail "generator did not detect an obsolete output"
fi
python3 "$ROOT/agent-rules/build.py" >/dev/null
[ ! -e "$STALE_RULE" ] || fail "generator did not remove an obsolete output"

resolve_script_dir() {
    printf '%s\n' "$ROOT"
}

# shellcheck source=../../install.d/10-helpers.sh
. "$ROOT/install.d/10-helpers.sh"
# shellcheck source=../../install.d/40-cursor.sh
. "$ROOT/install.d/40-cursor.sh"
# shellcheck source=../../install.d/50-claude.sh
. "$ROOT/install.d/50-claude.sh"
# shellcheck source=../../install.d/60-codex.sh
. "$ROOT/install.d/60-codex.sh"
# shellcheck source=../../install.d/65-opencode.sh
. "$ROOT/install.d/65-opencode.sh"

assert_scope_links() {
    scope=$1
    WORK_MACHINE=$2
    suffix=$3
    HOME="$TMP/$scope/home"
    XDG_CONFIG_HOME="$HOME/.config"
    export HOME XDG_CONFIG_HOME WORK_MACHINE

    setup_claude_config >/dev/null
    setup_codex_config >/dev/null
    setup_opencode_config >/dev/null

    [ "$(readlink "$HOME/.claude/CLAUDE.md")" = "$ROOT/claude/CLAUDE$suffix.md" ] || fail "Claude did not select $scope rules"
    [ "$(readlink "$HOME/.codex/AGENTS.md")" = "$ROOT/codex/AGENTS$suffix.md" ] || fail "Codex did not select $scope rules"
    [ "$(readlink "$XDG_CONFIG_HOME/opencode/AGENTS.md")" = "$ROOT/opencode/AGENTS$suffix.md" ] || fail "OpenCode did not select $scope rules"
}

assert_scope_links personal 0 ""
assert_scope_links work 1 "-work"

work_opencode_skill="$TMP/work/home/.config/opencode/skills/vanta-doc-discovery/SKILL.md"
[ -L "$work_opencode_skill" ] || fail "OpenCode did not link the work-only Doc Discovery adapter"
[ "$(readlink "$work_opencode_skill")" = "$ROOT/opencode/skills/vanta-doc-discovery/SKILL.md" ] || fail "OpenCode linked the wrong Doc Discovery adapter"
[ ! -e "$TMP/personal/home/.config/opencode/skills/vanta-doc-discovery/SKILL.md" ] || fail "personal OpenCode setup included Doc Discovery"

HOME="$TMP/opencode-skill-collision/home"
XDG_CONFIG_HOME="$HOME/.config"
WORK_MACHINE=1
export HOME XDG_CONFIG_HOME WORK_MACHINE
collision_skill="$XDG_CONFIG_HOME/opencode/skills/vanta-doc-discovery/SKILL.md"
mkdir -p "$(dirname "$collision_skill")"
printf 'unmanaged skill\n' >"$collision_skill"
setup_opencode_config >/dev/null
[ -L "$collision_skill" ] || fail "OpenCode did not link Doc Discovery over the preserved collision"
[ "$(cat "$collision_skill.pre-dotfiles")" = "unmanaged skill" ] || fail "OpenCode did not preserve the colliding skill"
setup_opencode_config >/dev/null
WORK_MACHINE=0
setup_opencode_config >/dev/null
[ ! -L "$collision_skill" ] || fail "personal OpenCode setup retained work-only Doc Discovery"
[ "$(cat "$collision_skill")" = "unmanaged skill" ] || fail "personal OpenCode setup did not restore the colliding skill"

HOME="$TMP/doc-discovery-plugin/home"
WORK_MACHINE=1
OBSIDIAN_ROOT="$TMP/obsidian"
export HOME WORK_MACHINE OBSIDIAN_ROOT
mkdir -p "$OBSIDIAN_ROOT/.claude/plugins/vanta-doc-discovery"
setup_vanta_doc_discovery_plugin >/dev/null
setup_vanta_doc_discovery_plugin >/dev/null
python3 - "$HOME/.claude/settings.json" <<'PY'
import json
import sys

with open(sys.argv[1], encoding="utf-8") as file:
    settings = json.load(file)

assert settings["enabledPlugins"]["vanta-doc-discovery@obsidian-local"] is True
PY
grep -qF 'setup_vanta_doc_discovery_plugin' "$ROOT/install.sh" || fail "installer does not run Doc Discovery setup"
grep -qF 'glean_default_search' "$ROOT/opencode/skills/vanta-doc-discovery/SKILL.md" || fail "OpenCode adapter does not map Glean search"
grep -qF 'glean_default_read_document' "$ROOT/opencode/skills/vanta-doc-discovery/SKILL.md" || fail "OpenCode adapter does not map Glean document reads"

HOME="$TMP/cursor/home"
XDG_CONFIG_HOME="$HOME/.config"
OS="linux"
WORK_MACHINE=1
export HOME XDG_CONFIG_HOME OS WORK_MACHINE
mkdir -p "$HOME/.cursor/rules"
printf 'unmanaged Cursor rule\n' >"$HOME/.cursor/rules/unmanaged.mdc"
printf 'colliding Cursor rule\n' >"$HOME/.cursor/rules/vanta-work.mdc"
setup_cursor >/dev/null
[ -L "$HOME/.cursor/rules/vanta-work.mdc" ] || fail "Cursor did not select work rules"
[ "$(cat "$HOME/.cursor/rules/vanta-work.mdc.pre-dotfiles")" = "colliding Cursor rule" ] || fail "Cursor did not preserve a colliding unmanaged rule"
WORK_MACHINE=0
setup_cursor >/dev/null
[ ! -L "$HOME/.cursor/rules/vanta-work.mdc" ] || fail "Cursor retained managed work rules in personal scope"
[ "$(cat "$HOME/.cursor/rules/vanta-work.mdc")" = "colliding Cursor rule" ] || fail "Cursor did not restore a colliding unmanaged rule"
[ -f "$HOME/.cursor/rules/unmanaged.mdc" ] || fail "Cursor removed an unmanaged rule"

HOME="$TMP/switch/home"
XDG_CONFIG_HOME="$HOME/.config"
WORK_MACHINE=0
export HOME XDG_CONFIG_HOME WORK_MACHINE
mkdir -p "$XDG_CONFIG_HOME/opencode/plugins"
printf 'unmanaged rules\n' >"$XDG_CONFIG_HOME/opencode/AGENTS.md"
setup_opencode_config >/dev/null
WORK_MACHINE=1
setup_opencode_config >/dev/null

[ "$(readlink "$XDG_CONFIG_HOME/opencode/AGENTS.md")" = "$ROOT/opencode/AGENTS-work.md" ] || fail "OpenCode did not switch managed rules to work scope"
[ "$(cat "$XDG_CONFIG_HOME/opencode/AGENTS.md.pre-dotfiles")" = "unmanaged rules" ] || fail "OpenCode changed the preserved unmanaged backup"

for agent in claude codex; do
    HOME="$TMP/$agent-unmanaged/home"
    XDG_CONFIG_HOME="$HOME/.config"
    WORK_MACHINE=0
    export HOME XDG_CONFIG_HOME WORK_MACHINE
    if [ "$agent" = "claude" ]; then
        mkdir -p "$HOME/.claude"
        printf 'unmanaged instructions\n' >"$HOME/.claude/CLAUDE.md"
        setup_claude_config >/dev/null
        target="$HOME/.claude/CLAUDE.md"
    else
        mkdir -p "$HOME/.codex"
        printf 'unmanaged instructions\n' >"$HOME/.codex/AGENTS.md"
        setup_codex_config >/dev/null
        target="$HOME/.codex/AGENTS.md"
    fi
    [ "$(cat "$target.pre-dotfiles")" = "unmanaged instructions" ] || fail "$agent did not preserve unmanaged instructions"
done

HOME="$TMP/claude-unmanaged-symlink/home"
XDG_CONFIG_HOME="$HOME/.config"
WORK_MACHINE=0
export HOME XDG_CONFIG_HOME WORK_MACHINE
mkdir -p "$HOME/.claude"
ln -s "$ROOT/README.md" "$HOME/.claude/CLAUDE.md"
setup_claude_config >/dev/null
[ "$(readlink "$HOME/.claude/CLAUDE.md.pre-dotfiles")" = "$ROOT/README.md" ] || fail "Claude did not preserve an unmanaged Dotfiles symlink"
