#!/bin/sh
set -eu

# Sync environment variables from the latest running Ona environment into a
# local shell fragment without echoing secret values. This is intended for
# work Cloud environments only.

if [ "${WORK_MACHINE:-}" != "1" ]; then
    echo "Skipping Ona env sync: WORK_MACHINE is not set to 1."
    exit 0
fi

if ! command -v ona >/dev/null 2>&1; then
    echo "Skipping Ona env sync: ona CLI is not installed."
    exit 0
fi

if ! command -v python3 >/dev/null 2>&1; then
    echo "Skipping Ona env sync: python3 is not installed."
    exit 0
fi

target_file=${ONA_ENV_FILE:-"$HOME/.ona_env"}
repository=${ONA_ENV_REPOSITORY:-"https://github.com/VantaInc/obsidian.git"}
branch=${ONA_ENV_BRANCH:-"main"}

environment_id=$(
    ona environment list --format json | python3 -c '
import json
import sys

repository = sys.argv[1]
branch = sys.argv[2]
environments = json.load(sys.stdin)

def timestamp(environment):
    metadata = environment.get("metadata", {})
    return metadata.get("lastStartedAt") or metadata.get("createdAt") or ""

matches = []
for environment in environments:
    spec = environment.get("spec", {})
    status = environment.get("status", {})
    initializer_specs = spec.get("content", {}).get("initializer", {}).get("specs", [])
    git_specs = [item.get("git", {}) for item in initializer_specs if isinstance(item, dict)]
    repo = next((item.get("remoteUri", "") for item in git_specs if item.get("remoteUri")), "")
    env_branch = next((item.get("cloneTarget", "") for item in git_specs if item.get("cloneTarget")), "")
    phase = status.get("phase") or environment.get("phase") or ""
    if phase in {"running", "ENVIRONMENT_PHASE_RUNNING"} and repo == repository and env_branch == branch:
        matches.append(environment)

if not matches:
    sys.exit("No running matching Ona environment found")

matches.sort(key=timestamp, reverse=True)
print(matches[0]["id"])
' "$repository" "$branch"
)

umask 077
ona environment ssh "$environment_id" -- bash -lc env | python3 -c '
import os
import shlex
import sys
from datetime import datetime, timezone

target_file = sys.argv[1]
environment_id = sys.argv[2]

deny_exact = {
    "HOME",
    "USER",
    "LOGNAME",
    "SHELL",
    "PWD",
    "PATH",
    "OLDPWD",
    "SHLVL",
    "_",
    "TERM",
    "HOSTNAME",
    "MAIL",
    "EUID",
    "UID",
    "PPID",
    "OPTERR",
    "OPTIND",
}
deny_prefixes = ("BASH", "DIRSTACK", "GROUPS", "PIPESTATUS", "SHELLOPTS")

exports = []
for raw_line in sys.stdin:
    line = raw_line.rstrip("\n")
    if "=" not in line:
        continue
    name, value = line.split("=", 1)
    if not name.isidentifier():
        continue
    if name in deny_exact or any(name.startswith(prefix) for prefix in deny_prefixes):
        continue
    exports.append((name, value))

exports.sort(key=lambda item: item[0])
tmp_file = f"{target_file}.tmp"
with open(tmp_file, "w", encoding="utf-8") as handle:
    handle.write("# Generated by sync_ona_env_from_ona.sh. Do not commit.\n")
    handle.write(f"# Source Ona environment: {environment_id}\n")
    handle.write(f"# Generated at: {datetime.now(timezone.utc).isoformat()}\n")
    for name, value in exports:
        handle.write(f"export {name}={shlex.quote(value)}\n")

os.chmod(tmp_file, 0o600)
os.replace(tmp_file, target_file)
os.chmod(target_file, 0o600)
' "$target_file" "$environment_id"

echo "Synced Ona env variable names to $target_file from $environment_id."
